language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - '8'
  - '10'
install:
  - yarn bootstrap
script:
  - yarn test-ci
notifications:
  email: false
git:
  depth: 5
env:
  global:
    secure: DC0GApSP1OrDiiae1OfovqNsPLqu4RVzIb2MSANZYo3xgc/HCwyujeqSwR1i+O1cJdSECTZCHJMprFtM8ctYdGsAkN0MZFaXazBefEVcsIXG06qYZcerbW5TkVvKBrxIQRMTVtxH3AMJuCsjRorUV70/K9Xxauwn8cNJxIRpFVvTtp5jrow6aPjwM3qMOZo/u6nn30epHAKoATRwjBUsP2HBSuBo6uJfmnW7j+GXoR9alxxr1CrFgIdIgG84XHOEIVEH/4XSA2zSIxAw+OVOqjIigNLDwT53glb5xc4WUBbrQjYT0zkOoB+UzpDGILOHyw38wyX75gdDftRDyBRjbsBfmELeFlyqQrSeM9W/HoERwWfh0Fw0vRupauj7CnIcJ16Y0MNvJ4mKLtk4lfUoBusthvC2wdPR+ze+QbGRde8dsGzJwkY9127WGoi4sZI4zje8YML4Pb3dnZ9gKPPDCQZBprScceE/N06ay0a0AuAcSETqUvSev2D338WR63jeT/ufhMQbEJNV6unAOTVcyejTd50Y3rUKzw1IqNOo0qx8kVILBT7/5TsmGwgk/UZ2cNcH8LBr02p6AVKvPtC60xG0v1KDWeLQ4gFqHa5qIgkTDIorI4DAvtdwKueMj6SEeuQKe9dWiHttI55vvQsAxUKGY3OSo6Skcsf7/dfa9so=
